### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by kassane** [kassane/bdwgc-d#3]
### TODO

- [ ] https://github.com/ivmai/bdwgc/issues/626
- [x] https://github.com/ivmai/bdwgc/issues/722
- [ ] https://github.com/ivmai/bdwgc/issues/547
- [x] Write `GCAllocator` (based on `std.experimental.mallocator`) - maybe rename to `BoehmAllocator` (??)
- [x] add benchmark between GCs (bdwgc x druntime)

**Comment by kassane** [comment]
>     * [ ]  add benchmark between GCs (bdwgc x druntime)

initial: https://github.com/kassane/bdwgc-d/commit/487641fbe0e4fb7677d6212b2cbd23e948c9d227

**Comment by kassane** [comment]
Removing support for `build.zig` makes building `libgc` less flexible by making the build static.
To get around the lack of this flexibility, it is recommended to use multi-config via dub, which allows the user to define the subConfiguration according to their needs.

**Comment by kassane** [comment]
Currently `BoehmAllocator` based on [`stdx-allocator`](https://github.com/dlang-community/stdx-allocator)/`std.experimental.allocator.mallocator` (malloc/free wrapper)

### What is the status of `std.experimental.allocator`?
https://forum.dlang.org/post/ubaunk$22qe$1@digitalmars.com

**Comment by kassane** [comment]
Since #5, `bdwgc-d` has been configuring the C project build directly in the dub environment without installing any extra build systems like `cmake`, `meson`, `build-zig`, etc... It has become a unique configuration, meaning it's not synchronized to the current `bdwgc` settings.
e.g.:
- `bdwgc-zig` use own build-system
- `bdwgc-rust` requires cmake to build

My point is that if configuring the base project requires a significant amount of work, Bindings are intended to align with the fundamental project parameters.
